config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  get 'bookings/show'
  devise_for :users
  root to: "pages#home"
  resources :bookings, only: [:show, :index, :destroy]
  resources :lessons, only: %i[index show] do
    resources :bookings, only: %i[create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
# app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
  has_one :review, dependent: :destroy

  DURATION_OPTIONS = [60, 90, 180].freeze
  STATUS_OPTIONS = %w(Pending Confirmed Completed).freeze

  validates :duration_minutes, inclusion: { in: DURATION_OPTIONS, message: 'must be 60, 90, or 180 minutes' }
  validates :status, inclusion: { in: STATUS_OPTIONS }

  # Additional Attributes
  validates :occurs_on, presence: true
  validates :is_online, inclusion: { in: [true, false] }
  validates :address, presence: true, if: -> { !is_online? }

  # Associations
  validates :user, presence: true
  validates :lesson, presence: true

  def calculate_total_cost
    hourly_rate * (duration_minutes.to_f / 60)
  end

  def is_confirmed?
    status == 'Confirmed'
  end

  def start_time
    occurs_on
  end

  def end_time
    occurs_on + duration_minutes.minutes
  end
end

app/models/lesson.rb
# app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  has_many :bookings

  VALID_SUBJECTS = %w(Maths English French Philosophy Biology Chemistry Physics).freeze

  validates :subject, presence: true, inclusion: { in: VALID_SUBJECTS }
  validates :description, presence: true, length: { in: 10..500 }
  validates :hourly_rate, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :comment, presence: true, length: { minimum: 10, maximum: 500 }
end

app/models/teacher_availability.rb
class TeacherAvailability < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :teacher_availability
  has_many :lessons
  has_many :bookings, through: :lessons
  has_many :reviews, through: :bookings
  validates :education_level, inclusion: { in: %w(Secondary Undergraduate Masters MBA PhD) }
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :education_level, :is_teacher, :bio, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :education_level, :is_teacher, :bio, :address])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_lesson, only: %i[create]
  before_action :authenticate_user!, only: %i[create]

  def index
    if current_user && current_user.is_teacher
      @bookings = Booking.where(lesson: current_user.lessons)
    else
      @bookings = Booking.where(user: current_user)

    end
  end

  def show
    # @bookings
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.lesson = @lesson
    @booking.user = current_user
    @booking.duration_minutes = 60
    @booking.status = "Confirmed"
    @booking.address = "At my place"
    if @booking.save
      redirect_to bookings_index_path
    else
      redirect_to lesson_path(@lesson), alert: "Pick a date and time"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_index_path, status: :see_other
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def booking_params
    params.require(:booking).permit(:occurs_on, :duration_minutes, :lesson_id, :user_id)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = params[:subject].present? ? Lesson.where(subject: params[:subject].capitalize) : Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
    @teacher_availabilities = TeacherAvailability.find_by(user: @lesson.user)
    @booking = Booking.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/bookings/index.html.erb
  <h1 class="heading">Upcoming Bookings</h1>

<div class="booking-container">
<% @bookings.each do |booking| %>
  <div class="card-booking">
    <div class="image-container">
      <%= image_tag booking.lesson.user.avatar_url, alt: "Teacher photo"%>
      <span class="box-rounded"><%=booking.status%></span>
      <p class="overlay-text"><strong><%= booking.lesson.user.first_name%> <%=booking.lesson.user.last_name %></strong></p>
    </div>
      <div class="card-booking-infos">
        <span class="card-booking-span"><%=booking.lesson.subject %></span> -
        <span><%=booking.lesson.description %></span>
    </div>
      <p class="info-text"><strong>Booked:</strong> <%=booking.start_time.strftime("%A, %B %e, %Y") %>
      <br>
        <strong>Address:</strong> <%= booking.lesson.user.address%>
      <br>
        <strong>Duration:</strong> <%= booking.duration_minutes %>
      <br>
        <strong>Price: </strong><%="#{booking.lesson.hourly_rate} €"%> </p>

    <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
    <i class="fa-regular fa-trash-can"></i>
    <% end %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elevate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/9b8a7e18a0.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <% if flash.present? %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= render "shared/navbar" %>
    <% if current_user %>
      <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},  class: "btn btn-secondary logout-button" %>
    <% end %>

    <% unless params[:controller] == "pages" && params[:action] == "home" %>
      <%# <div class="container"> %>
    <% end %>

    <div style="margin-bottom: 70px"> <%# margin is the same as navbar height  %>
      <%= yield %>
    </div>

    <% unless params[:controller] == "pages" && params[:action] == "home" %>
      <%# </div> %>
    <% end %>
  </body>
</html>

app/views/lessons/index.html.erb
<h1 class="heading"><%= params[:subject].present? ? params[:subject].capitalize : "All" %> lessons</h1>
  <div class="booking-container">

  <% @lessons.each do |lesson| %>
    <%=link_to lesson_path(lesson), style: "text-decoration: none;", class: "card-lesson-link" do%>
      <div class="card-lesson" >
        <%= image_tag lesson.user.avatar_url, alt: "Teacher photo"%>
        <span class="box-rounded-3">
          <i class="fa-solid fa-coins"></i>   <%="#{lesson.hourly_rate}€/hour"%>
        </span>
        <p><strong><%=lesson.user.first_name%> <%=lesson.user.last_name%></strong></p>
      <div class="card-lesson-infos">
        <span><%=lesson.subject%></span> -
        <span><%=lesson.description%></span>
      </div>
      </div>
    <% end %>
  <% end %>
</div>

<strong></strong>

app/views/lessons/show.html.erb
<div class="d-flex flex-column">
  <div class="card-teacher-intro">
    <div class="simple-box"></div>
    <%= image_tag @lesson.user.avatar_url, class: "avatar-large", alt: "Teacher photo"%>
    <h2 class="subheading"><%= "#{@lesson.user.first_name} #{@lesson.user.last_name}" %></h2>
  </div>

  <div class="card-teacher-about m-4">
    <div class="teacher-tags">
      <span class="box-rounded">
        <i class="fa-solid fa-pencil" style="color: $primary;"></i> <%= @lesson.subject %>
      </span>
      <span class="box-rounded">
        <i class="fa-solid fa-graduation-cap icon" style="color: $primary;"></i>   <%=@lesson.user.education_level%>
      </span>
      <span class="box-rounded">
        <i class="fa-solid fa-coins" style="color: $primary;"></i>   <%="#{@lesson.hourly_rate}€/hour"%>
      </span>
    </div>
  </div>

  <div class="card-lesson-about">
    <h3><%="About #{@lesson.user.first_name}"%></h3>
    <p><%=@lesson.user.bio%></p>
    <h3 class="mt-3">Lesson Details</h3>
    <p><%=@lesson.description %></p>
  </div>

  <div class="card-teacher-availability">
    <h3><%="#{@lesson.user.first_name}'s Availability"%></h3>
    <%@teacher_availabilities.attributes.select { |key, value| value == true}.keys.each do |key|%>
      <% day_array = key.split("_") %>
      <span class="box-rounded-2"><%= "#{day_array[0].capitalize} #{day_array[1] == "am" ? "morning" : "afternoon"}" %></span>
    <%end%>
  </div>

  <div class="book-now m-4">
    <h3><%= "Book Now With #{@lesson.user.first_name}" %></h3>
    <%= simple_form_for [@lesson, @booking] do |f|%>
      <div class="booking-form">
        <%= f.input :occurs_on,
                    label: false,
                    as: :string,
                    input_html: { data: { controller: "datepicker" }, placeholder: "Select date and time" } %>
        <i class="fa-solid fa-calendar-days"></i>
        <%= f.submit 'Book', class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="homepage" id="bk-img">
  <div class="head">
  </div>

    <h1 class="title">Elevate.</h1>


    <%= form_with url: lessons_path, method: :get, class: "d-flex text_and_icon flex-container item-flex" do %>
      <%= select_tag "subject", options_for_select(Lesson::VALID_SUBJECTS), #Lesson.all.pluck(:subject).uniq
            class: "form-control",
            prompt: "What do you want to learn?"
        %>
            <div class="line"></div>

      <%= button_tag(type: "submit", name: "search", class: "btn flex-item text_and_icon") do %>
        <%= content_tag(:i, "", class: "fas fa-search search_icon") %>
      <% end %>
    <% end %>


  <div class="bottom">
    <p class="slogan" >Find a teacher near you and unlock your true potential today</p>
  </div>

</div>

app/views/shared/_navbar.html.erb
  <nav class="navbar fixed-bottom navbar-light">

          <%# chat %>
          <%= link_to root_path, class: "nav-link" do  %>
            <i class="fas fa-comment-alt"></i> <span></span>
          <% end %>
   
          <%= link_to root_path, class: "nav-link" do %> 
            <i class="fa-solid fa-magnifying-glass"></i> <span></span>
          <% end %>

          <%= link_to bookings_path, class: "nav-link" do %> 
            <i class="fa-solid fa-calendar-days"></i> <span></span>
          <% end %>

          <%= link_to user_session_path, class: "nav-link" do %> 
            <i class="fa-solid fa-user"></i>
          <% end %>
  </nav>